<?php
/** @var \MageSuite\ThemeHelpers\Block\Icon $block */

$altText = $block->getAltText() ?? '';
$cssClasses = $block->getCssClass();
$shouldInline = $block->getInlined();
$shouldLazyLoad = $block->getLazyLoaded() ?? true;
$width = $block->getWidth() ?? null;
$height = $block->getHeight() ?? null;
$iconPath = $block->getIconPath();
$isRemoteUrl = strpos($iconPath, 'http') === 0;

if ($iconPath && $shouldInline && !$shouldLazyLoad && !$isRemoteUrl) {
    $inlineSvg = $block->getViewFileContents($iconPath);

    if (strpos($inlineSvg, 'class="') !== false) {
        $inlineSvg = str_replace('class="', 'class="' . $cssClasses . ' ', $inlineSvg);
    } else {
        $inlineSvg = str_replace('<svg', '<svg class="' . $cssClasses . '"', $inlineSvg);
    }

    if ($altText) {
        $inlineSvg = str_replace('<svg', '<svg aria-label="' . $altText . '"', $inlineSvg);
    }

    echo $inlineSvg;
} else {
    $iconUrl = $block->getIconUrl();

    if ($shouldInline) {
        $cssClasses .= ' inline-svg';
    } elseif ($shouldLazyLoad) {
        $cssClasses .= ' lazyload';
    }

    if ($shouldLazyLoad || $shouldInline) : ?>
        <img
            class="<?= $cssClasses; ?>"
            src="data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs="
            data-src="<?= $iconUrl; ?>"
            alt="<?= $altText; ?>"
            <?php if ($width && $height) : ?>width="<?= $width ?>"<?php endif; ?>
            <?php if ($width && $height) : ?>height="<?= $height ?>"<?php endif; ?>
        >
        <noscript>
            <img
                class="<?= $cssClasses; ?>"
                src="<?= $iconUrl; ?>"
                alt="<?= $altText; ?>"
            >
        </noscript>
    <?php else : ?>
        <img
            class="<?= $cssClasses; ?>"
            src="<?= $iconUrl; ?>"
            alt="<?= $altText; ?>"
            <?php if ($width && $height) : ?>width="<?= $width ?>"<?php endif; ?>
            <?php if ($width && $height) : ?>height="<?= $height ?>"<?php endif; ?>
        >
    <?php endif;
}
