<?php
    $additionalCssClasses = $block->getAdditionalCssClasses();
    $showLabel = $block->getShowLabel();
?>

<div class="cs-page-scroll <?= $additionalCssClasses; ?>">
    <div class="cs-page-scroll__button">
        <span class="cs-page-scroll__text<?php if(!$showLabel): ?> cs-visually-hidden<?php endif; ?>"><?= __('Go to top'); ?></span>
        <div class="cs-page-scroll__icon-wrapper">
            <?= $block->getChildHtml(); ?>
        </div>
    </div>
</div>
