<?php
    $decrementIconUrl = $block->getDecrementIconUrl();
    $incrementIconUrl = $block->getIncrementIconUrl();
?>
<div class="cs-qty-increment <?= $escaper->escapeHtmlAttr($block->getAdditionalCssClasses()) ?>">
    <input type="number"
           name="<?= $escaper->escapeHtmlAttr($block->getInputName()); ?>"
           class="cs-qty-increment__input <?= $escaper->escapeHtmlAttr($block->getAdditionalInputCssClasses()); ?>"
           aria-label="<?= $escaper->escapeHtmlAttr($block->getLabel()); ?>"
           value="<?= $escaper->escapeHtmlAttr($block->getInputInitialValue()); ?>"
           title="<?= $escaper->escapeHtmlAttr($block->getTitle()); ?>"
           <?= /* @noEscape */ $block->getInputAdditionalParams(); ?>
    >

    <?= /* @noEscape */ $block->getChildHtml(''); ?>

    <?php if ($decrementIconUrl && !empty($decrementIconUrl)) : ?>
        <span role="button" tabindex="0" class="cs-qty-increment__button cs-qty-increment__button--decrement" aria-pressed="false">
            <?= /* @noEscape */ $block->getLayout()
                 ->createBlock(\MageSuite\ThemeHelpers\Block\Icon::class)
                 ->setIconUrl($decrementIconUrl)
                 ->setCssClass('cs-qty-increment__icon cs-qty-increment__icon--decrement')
                 ->setAltText(__('Decrease quantity by one'))
                 ->setInlined(true)
                 ->setLazyLoaded(false)
                 ->toHtml(); ?>
        </span>
    <?php endif; ?>

    <?php if ($incrementIconUrl && !empty($incrementIconUrl)) : ?>
        <span role="button" tabindex="0" class="cs-qty-increment__button cs-qty-increment__button--increment" aria-pressed="false">
            <?= /* @noEscape */ $block->getLayout()
                 ->createBlock(\MageSuite\ThemeHelpers\Block\Icon::class)
                 ->setIconUrl($incrementIconUrl)
                 ->setCssClass('cs-qty-increment__icon cs-qty-increment__icon--increment')
                 ->setAltText(__('Increase quantity by one'))
                 ->setInlined(true)
                 ->setLazyLoaded(false)
                 ->toHtml(); ?>
        </span>
    <?php endif; ?>
</div>
