<?php
    $decrementIconUrl = $block->getDecrementIconUrl();
    $incrementIconUrl = $block->getIncrementIconUrl();
    $uniqueId = 'qty-increment-' . bin2hex(random_bytes(5));
?>
<div class="cs-qty-increment <?= $block->getAdditionalCssClasses() ?>">

    <!-- Hidden label added for better accessablity -->
    <label for="<?= $uniqueId ?>" class="cs-qty-increment__label"><?= __('Quantity input') ?></label>

    <input type="number" 
           name="<?= $block->getInputName() ?>" 
           size="<?= $block->getInputSize() ?? 3 ?>" 
           class="cs-qty-increment__input <?= $block->getAdditionalInputCssClasses() ?>" 
           id="<?= $uniqueId ?>" 
           value="<?= $block->getInputInitialValue() ?>"
           <?= $block->getInputAdditionalParams() ?>
    >

    <?= $block->getChildHtml(''); ?>

    <?php if ($decrementIconUrl && !empty($decrementIconUrl)): ?>
        <span role="button" tabindex="0" class="cs-qty-increment__button cs-qty-increment__button--decrement" aria-pressed="false">
            <?= $this->getLayout()
                 ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                 ->setIconUrl($decrementIconUrl)
                 ->setCssClass('cs-qty-increment__icon cs-qty-increment__icon--decrement')
                 ->setAltText(__('Decrement product quantity icon'))
                 ->setInlined(true)
                 ->setLazyLoaded(false)
                 ->toHtml(); ?>
        </span>
    <?php endif; ?>

    <?php if ($incrementIconUrl && !empty($incrementIconUrl)): ?>
        <span role="button" tabindex="0" class="cs-qty-increment__button cs-qty-increment__button--increment" aria-pressed="false">
            <?= $this->getLayout()
                 ->createBlock('MageSuite\ThemeHelpers\Block\Icon')
                 ->setIconUrl($incrementIconUrl)
                 ->setCssClass('cs-qty-increment__icon cs-qty-increment__icon--increment')
                 ->setAltText(__('Increment product quantity icon'))
                 ->setInlined(true)
                 ->setLazyLoaded(false)
                 ->toHtml(); ?>
        </span>
    <?php endif; ?>
</div>
