<?php
/** @var $block \MageSuite\ThemeHelpers\Block\Category\View\Headline */
?>
<div class="page-title-wrapper cs-page-title cs-page-title--page-category <?= $block->getAdditionalCssClasses() ?>">
    <h1 class="page-title cs-page-title__headline" id="page-title-heading" aria-labelledby="page-title-heading">
        <span class="base" data-ui-id="page-title-wrapper"><?= $block->getHeadline() ?> </span>
        <?php if($block->getShowCollectionSize()): ?>
            <span class="secondary page-title__span">(<?= $block->getCollectionSize() ?>)</span>
        <?php endif; ?>
    </h1>
</div>
